name: "Jest Code Coverage Report"
description: "Comments a pull request with the jest code coverage"
author: "Zeeshan Ahmad"
branding:
  icon: "check-square"
  color: "green"
inputs:
  github-token:
    description: "Github token"
    required: true
  input-folder:
    description: "Input report folder path"
    required: true
  output-folder:
    description: "Output report folder path"
    required: true
runs:
  using: "node12"
  main: "index.js"